name: Release Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # build project
    - name: mkdir
      run: mkdir build
    - name: cmake build
      run: cmake -B build -S.
    - name: cmake make
      run: cmake --build build/ --target all  --config Release
      env:
        MAKEFLAGS: "-j2"
